### ISSUE TITLE
DashR does not currently have the `get_asset_url` method for loading asset URLs like Dash for Python

### ISSUE THREAD

**Issue by HammadTheOne** [plotly/dashR#158]
As originally referenced in a DashR docs issue, Dash for R currently lacks this method which is featured in the Python version. Based on the Python implementation, it would grab the asset URL from the assets directory without needing to specify the exact path. 

> @rpkyle @HammadTheOne - Do you think we could get a `get_asset_url` into Dash for R before the next release? Here is the implementation in Python:
> https://github.com/plotly/dash/blob/e622f2a31202302d0c305c56e738d1ea369403e6/dash/dash.py#L1559-L1566
> 
> If it's not in Dash for R, then we can include it in this example as a helper function.
> 

_Originally posted by @chriddyp in https://github.com/plotly/dash-enterprise-docs/pull/95_

**Comment by rpkyle** [comment]
Thanks @HammadTheOne -- I meant to reply earlier; just did that now.

It's correct to say that Dash for R doesn't have this _method_, because the function isn't associated with the `Dash` R6 class, but rather an unexported function in `utils.R`:

https://github.com/plotly/dashR/blob/5f2942c1eef0c38653d74b5cb5b658bfaacfbed5/R/utils.R#L583-L598

@HammadTheOne I can make this change via PR, and will ask you for review.

**Comment by rpkyle** [comment]
Thanks @HammadTheOne -- I've responded in the original thread, but I think I'll have to add in a check for the names attribute to make this usable by developers, even if exported. If there is no name associated with the path, the function will infer it from the asset map, otherwise it will use the one passed.

**Comment by rpkyle** [comment]
Closed by way of https://github.com/plotly/dashR/pull/160.
