### ISSUE TITLE
3d surface plot "changes" in editor mode

### ISSUE THREAD

**Issue by Attia81** [plotly/dashR#245]
Hello

I have a 3d surface plot that is different in viewer mode and editor mode. The viewer mode is the correct one but when in editor mode it is wrong, why is it?

in viewer mode looks like this
https://chart-studio.plotly.com/~aattia81/46.embed

in editor mode is switched to this

https://chart-studio.plotly.com/create/?fid=aattia81:46

Any ideas!

**Comment by alexcjohnson** [comment]
Very strange - for some reason the editor is transposing the `z` array

**Comment by dmt0** [comment]
Tried rendering the figure directly in [React Chart Editor](https://github.com/plotly/react-chart-editor), displays fine:

![image](https://user-images.githubusercontent.com/2717746/106819808-4f5b6400-6648-11eb-93c6-983fd3d2d6c7.png)

**Comment by Attia81** [comment]
Can you please elaborate more on the steps?

This what I get?

**Comment by dmt0** [comment]
@Attia81 This was not done in Chart Studio. Anyway:

1. `git clone` the React Chart Editor repo (this is the component we use for chart editing in Chart Studio)
2. `yarn install`
3. `yarn start`
4. Copy paste your figure into the JSON panel as in the screenshot above.

The comment above was meant to show that the issue is not in plotly.js and not in RCE but somewhere in Chart Studio internals.

**Comment by rpkyle** [comment]
Thanks a lot @dmt0! @Attia81 we've opened an issue internally for Chart Studio, so will close this one as a duplicate.
