### ISSUE TITLE
Error in app$index_string <- index_string :    cannot change value of locked binding for 'index_string'

### ISSUE THREAD

**Issue by jrosell** [plotly/dashR#247]
An error on documentation https://dashr.plotly.com/external-resources.
Instead of: app$index_string <- string 
Put: app$index_string(string)

**Comment by rpkyle** [comment]
Hi @jrosell! Thanks for reporting this error. It actually looks to appear in two locations:

https://github.com/plotly/dash-docs/blob/6dbdcb62ba270e4c1ed9bf54ccd065f76df3d970/dash_docs/chapters/external_resources/examples/custom-index-string.R#L31
https://github.com/plotly/dash-docs/blob/6dbdcb62ba270e4c1ed9bf54ccd065f76df3d970/dash_docs/chapters/external_resources/index.R#L251

If you're interested in submitting a PR to update these, I'm happy to review, otherwise I can make the change.
