### ISSUE TITLE
Missing 3 Dash app parameters, should support for full parity with Python

### ISSUE THREAD

**Issue by TahiriNadia** [plotly/dashR#69]
```
app.index_string = '''
<!DOCTYPE html>
<html>
    <head>
        {%metas%}
        <title>{%title%}</title>
        {%favicon%}
        {%css%}
    </head>
    <body>
        <div>My Custom header</div>
        {%app_entry%}
        <footer>
            {%config%}
            {%scripts%}
            {%renderer%}
        </footer>
        <div>My Custom footer</div>
    </body>
</html>
'''
```

I'm trying `app$index_string` but not found?

**Comment by rpkyle** [comment]
@TahiriNadia Good catch. I think we're missing the following parameters, which I should add for parity with Dash for Python. 

We hadn't done it yet because it wasn't a task item for the initial release, but now's a good time to bolt down the API and round off the loose edges.

So, we're actually missing a few options here:

```
compress=True,
meta_tags=None,
index_string=_default_index
```

I'll slide this onto the project board so we keep track of this issue.

**Comment by rpkyle** [comment]
The parameters required were added in https://github.com/plotly/dashR/pull/157, https://github.com/plotly/dashR/pull/168, and https://github.com/plotly/dashR/pull/142. Closing.
